# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake0

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push: { branches: [ "master", "main" ] }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # github user name to read the contribution graph from (**required**)
          # using action context var `github.repository_owner` or specified user
          github_user_name: ${{ github.repository_owner }}

          outputs: |
            contribution-snake/github-snake.svg
            contribution-snake/github-snake-dark.svg?palette=github-dark
            contribution-snake/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

        env:
          # a github token is required to fetch the contribution calendar from github API
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
